#!/usr/bin/env bash
#
# Trades — the agent-role lane (IA-010; production-infrastructure-first-deploy BR-27, AC-14):
# the masked read-only database role an AI-agent session may use, provisioned on the host by
# the OPERATOR after the first `app` promotion and after EVERY later migration or inventory
# change (Phase 7 step 11; RUNBOOK.md § "The agent-role lane").
#
#   sudo -u deploy /srv/trades/deploy/agent-db/provision-agent-role.sh
#
# What it does:
#   1. reads the role's password from /srv/trades/secrets/ai-readonly.env (mode 600,
#      `AI_READONLY_PASSWORD=…`, generated by the operator) — never an argument, never printed;
#   2. applies agent-readonly-role.sql inside the postgres container (idempotent: creates or
#      re-asserts the role, revokes every non-system schema, withdraws CONNECT on `media` from
#      PUBLIC, self-verifies the boundary);
#   3. runs generate-masked-views.sh over deploy/agent-db/mask-manifest.txt (fail-closed: a
#      manifest column missing from the live table ABORTS — fix pii-inventory.md, regenerate);
#   4. prints the SHAPE of the masked DSN and the HUMAN step that brokers it: the operator
#      writes it by hand to the SecureString parameter /trades/production/agent/database-url
#      (OUTSIDE env/* — the one path the agent role may read). The password never appears in
#      this script's output.
#
# How a session reaches it (spec § Open Questions): the Postgres port is never published and
# the agent role is denied SSM sessions, so the developer opens an SSM port-forward under the
# OPERATOR profile and hands the agent the local port and the masked DSN for the session.
#
# Env (optional): COMPOSE_DIR (the deploy directory), AI_READONLY_ENV_FILE
# (/srv/trades/secrets/ai-readonly.env). IA-004: never run from an agent session.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
COMPOSE_DIR="${COMPOSE_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
COMPOSE=(docker compose --project-directory "$COMPOSE_DIR" -f "$COMPOSE_DIR/docker-compose.prod.yml")
AI_READONLY_ENV_FILE="${AI_READONLY_ENV_FILE:-/srv/trades/secrets/ai-readonly.env}"

log() { printf '→ agent-role: %s\n' "$*"; }
die() { printf '✗ agent-role: %s\n' "$*" >&2; exit 1; }

[ -n "$("${COMPOSE[@]}" ps -q postgres 2>/dev/null)" ] || die "the postgres container is not running — the lane runs after the first app promotion"
[ -f "$SCRIPT_DIR/agent-readonly-role.sql" ] || die "$SCRIPT_DIR/agent-readonly-role.sql missing (sync the host: scripts/sync-host-deploy.sh)"
[ -x "$SCRIPT_DIR/generate-masked-views.sh" ] || die "$SCRIPT_DIR/generate-masked-views.sh missing or not executable"
[ -f "$SCRIPT_DIR/mask-manifest.txt" ] || die "$SCRIPT_DIR/mask-manifest.txt missing — generate it in trades-infra (make mask-manifest) and sync the host"

# --- 1. the password ---------------------------------------------------------------------
[ -f "$AI_READONLY_ENV_FILE" ] || die "$AI_READONLY_ENV_FILE missing — write it from a generated value (mode 600): AI_READONLY_PASSWORD=<generated>"
mode="$(stat -c '%a' "$AI_READONLY_ENV_FILE" 2>/dev/null || stat -f '%Lp' "$AI_READONLY_ENV_FILE" 2>/dev/null || echo '?')"
[ "$mode" = 600 ] || die "$AI_READONLY_ENV_FILE must be mode 600 (is $mode)"
AI_READONLY_PASSWORD="$(grep -E '^AI_READONLY_PASSWORD=' "$AI_READONLY_ENV_FILE" | head -1 | cut -d= -f2- || true)"
[ -n "$AI_READONLY_PASSWORD" ] || die "$AI_READONLY_ENV_FILE carries no AI_READONLY_PASSWORD= line"
[ "${#AI_READONLY_PASSWORD}" -ge 24 ] || die "AI_READONLY_PASSWORD is shorter than 24 characters"
export AI_READONLY_PASSWORD   # inherited by the docker client below through `-e NAME` (name only)

# --- 2. the role (inside the container) --------------------------------------------------------
# The value never rides a process command line: the docker client receives `-e AI_READONLY_PASSWORD`
# (the NAME only — the value comes from the exported variable, invisible in the host's process
# list; the same shape seed-synthetic.sh uses), and inside the container psql receives it through
# -v, never argv.
log "applying agent-readonly-role.sql (idempotent; revokes every non-system schema, self-verifies)"
# shellcheck disable=SC2016  # the container's own POSTGRES_USER; -v carries the password INTO psql's variable, quoted by :'var'
"${COMPOSE[@]}" exec -T -e AI_READONLY_PASSWORD postgres \
  sh -c 'psql -U "$POSTGRES_USER" -d trades_app -v ON_ERROR_STOP=1 -v ai_readonly_password="$AI_READONLY_PASSWORD" -f -' \
  < "$SCRIPT_DIR/agent-readonly-role.sql" \
  || die "agent-readonly-role.sql failed — read the error above (a schema that does not exist yet means the migrations have not run; a BOUNDARY BROKEN exception means a grant to PUBLIC exists)"

# --- 3. the views --------------------------------------------------------------------------
log "regenerating the mask views from mask-manifest.txt"
COMPOSE_FILE="$COMPOSE_DIR/docker-compose.prod.yml" "$SCRIPT_DIR/generate-masked-views.sh" "$SCRIPT_DIR/mask-manifest.txt" \
  || die "generate-masked-views.sh aborted — a stale inventory row? Fix trades-docs/pii-inventory.md, regenerate the manifest (make mask-manifest), sync the host, re-run"

# --- 4. the brokered DSN (HUMAN) -------------------------------------------------------------
container_ip="$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$("${COMPOSE[@]}" ps -q postgres)" 2>/dev/null || echo '<postgres container ip>')"
echo ""
echo "✓ agent-role: ai_readonly provisioned and the mask schema regenerated."
echo "  HUMAN — broker the masked DSN under its own parameter path (OUTSIDE env/*), from a throwaway file, never one value on a command line:"
echo "    printf '%s' \"postgresql://ai_readonly:<AI_READONLY_PASSWORD>@127.0.0.1:55432/trades_app\" > dsn.txt"
echo "    aws ssm put-parameter --region eu-south-2 --type SecureString --name /trades/production/agent/database-url --value file://dsn.txt --overwrite && rm -f dsn.txt"
echo "  127.0.0.1:55432 is the LOCAL end of an operator-opened SSM port-forward to the postgres container (bridge IP ${container_ip}, port 5432):"
echo "    aws ssm start-session --region eu-south-2 --target <instance-id> --document-name AWS-StartPortForwardingSessionToRemoteHost --parameters '{\"host\":[\"${container_ip}\"],\"portNumber\":[\"5432\"],\"localPortNumber\":[\"55432\"]}'"
echo "  Verify (AC-14): SET ROLE ai_readonly; SELECT * FROM identity.users;  -- permission denied;  SELECT * FROM shared.messenger_messages;  -- un-inventoried: no view, denied;  \\c media  -- refused"
