#!/usr/bin/env bash
# Caddyfile gate — `caddy adapt` in the digest-pinned Caddy image, then READ the adapted JSON
# (production-packaging-promotion-lane BR-25; rewritten by production-infrastructure-first-deploy
# for the stage-1 perimeter, BR-20 / BR-36). The exit code of `caddy validate` proves the file
# parses; it proves nothing about what the log lines carry (the template's lexer trap: a wrong
# escape makes the uri filter fail OPEN with "Valid configuration") nor about WHICH host carries
# basic auth. So the checks below assert the adapted config's SHAPE:
#   1. adapts cleanly with the rehearsal AND the production arguments (TLS e-mail, a real
#      bcrypt hash — never a credential, a hash of a throwaway string generated in the image)
#   2. the query-string filter on request>uri is present, with the `[?].*$` pattern, on every
#      logger (five site loggers + the default one)
#   3. remote_ip AND client_ip are ip_mask'ed (both, on every logger)
#   4. the file writer carries BOTH ceilings: roll_interval (24h) and roll_keep_days (14)
#   5. every site block has a logger (Caddy logs nothing without one) — FIVE hosts
#   6. the (security_floor) is present IN DEFERRED (`?`) FORM at site level AND inside every
#      handle_errors — all six headers, on all five hosts, on both lanes (BR-20)
#   7. every error lane answers a bare `{err.status_code} {err.status_text}` and is marked
#      `Cache-Control: private, no-store` (AS-028, SE-004)
#   8. `X-Robots-Tag: noindex` on every site (BR-18)
#   9. basic auth on EXACTLY app. and mail. — present there, absent on api. / media. / storage.
#      (BR-18: HTTP Basic and the API's Bearer token share the Authorization header)
#  10. no unconditional (non-`?`) Content-Security-Policy anywhere (CSP is application-emitted;
#      the floor is a deferred default), and exactly ONE unconditional HSTS writer — the storage
#      host's explicit block (BR-32 of 10.4)
#
# Usage: scripts/checks/check-caddyfile.sh [deploy/Caddyfile]
# Needs docker. Fails closed: no docker → red.

set -euo pipefail

cd "$(dirname "$0")/../.."
CADDYFILE="${1:-deploy/Caddyfile}"
CADDY_IMAGE="${CADDY_IMAGE:-caddy:2.11@sha256:0c994536bddb66445885237f1a5dcc1916bccea922661c76b4e9fc24061f9b52}"
HOSTS="app api media storage mail"
AUTH_HOSTS="app mail"
FLOOR_HEADERS="Strict-Transport-Security Content-Security-Policy X-Content-Type-Options Referrer-Policy Cross-Origin-Opener-Policy Cross-Origin-Resource-Policy"

[ -f "$CADDYFILE" ] || { echo "✗ check-caddyfile: $CADDYFILE not found" >&2; exit 2; }
command -v docker >/dev/null 2>&1 || { echo "✗ check-caddyfile: docker not found — the check runs Caddy as a container and does not skip" >&2; exit 1; }

# A real bcrypt hash of a throwaway string, generated by the pinned image — the Caddyfile's
# basic_auth needs a well-formed hash to adapt. Not a credential: nothing is deployed with it.
HASH="$(docker run --rm "$CADDY_IMAGE" caddy hash-password -p 'check-caddyfile-throwaway' 2>/dev/null)" \
  || { echo "✗ check-caddyfile: could not generate a throwaway hash in $CADDY_IMAGE" >&2; exit 1; }

adapt() {
  docker run --rm -v "$PWD/$CADDYFILE:/etc/caddy/Caddyfile:ro" \
    -e "DOMAIN=$1" -e "CADDY_TLS_ARG=$2" -e "BASIC_AUTH_USER=operator" -e "BASIC_AUTH_HASH=$HASH" \
    "$CADDY_IMAGE" caddy adapt --config /etc/caddy/Caddyfile 2>&1
}

json_prod="$(adapt example.com ops@example.com)" || { echo "✗ check-caddyfile: adapt failed (production args):"; echo "$json_prod"; exit 1; }
json_reh="$(adapt trades.test internal)" || { echo "✗ check-caddyfile: adapt failed (rehearsal args):"; echo "$json_reh"; exit 1; }
echo "→ caddy adapt: OK (production + rehearsal arguments)"

# `caddy adapt` prints COMPACT JSON and Go's encoder escapes the greater-than sign as
# backslash-u-0-0-3-e — every pattern below is a FIXED STRING (grep -F) matched against exactly
# that shape. The escape is BUILT here from an octal byte rather than typed: a literal
# backslash-u sequence in this file is one some editing tool chains silently turn back into the
# bare sign (observed 2026-10-02 — the gate then reads 0 loggers and fails), and a check that
# cannot find its own pattern is worse than one that spells it out. `|| true` keeps a zero-count
# from ending the script under pipefail: zero is a verdict, not an error.
GT="$(printf '\134')u003e"
count() { printf '%s' "$1" | grep -oF -- "$2" | wc -l | tr -d ' ' || true; }
count_re() { printf '%s' "$1" | grep -oE -- "$2" | wc -l | tr -d ' ' || true; }

fails=0
check() {   # check <ok?> <message>
  if [ "$1" = 0 ]; then echo "  ✓ $2"; else echo "  ✗ $2" >&2; fails=$((fails + 1)); fi
}
ok_if() { if [ "$1" = 0 ]; then echo 0; else echo 1; fi; }   # arithmetic result → check flag

# 2. query-string filter on request>uri (the exact pattern; a re-escaped one fails open)
n="$(count "$json_reh" '"request'"$GT"'uri":{"filter":"regexp","regexp":"[?].*$"}')"
check "$([ "$n" -ge 6 ] && echo 0 || echo 1)" "request>uri regexp filter '[?].*\$' present on every logger ($n found, need >=6: 5 site loggers + default)"

# 3. both IP fields masked, /24 and /48
n_remote="$(count "$json_reh" '"request'"$GT"'remote_ip":{"filter":"ip_mask","ipv4_cidr":24,"ipv6_cidr":48}')"
n_client="$(count "$json_reh" '"request'"$GT"'client_ip":{"filter":"ip_mask","ipv4_cidr":24,"ipv6_cidr":48}')"
check "$([ "$n_remote" -ge 6 ] && [ "$n_client" -ge 6 ] && echo 0 || echo 1)" "remote_ip and client_ip ip_mask'ed /24 /48 on every logger (remote=$n_remote client=$n_client, need >=6)"

# 4. both roll ceilings on the file writer (Caddy's JSON: roll_interval in ns, roll_keep_days)
n_int="$(count "$json_reh" '"roll_interval":86400000000000')"
n_days="$(count "$json_reh" '"roll_keep_days":14')"
check "$([ "$n_int" -ge 1 ] && [ "$n_days" -ge 1 ] && echo 0 || echo 1)" "file writer carries roll_interval=24h and roll_keep_days=14 (the 14-day ceiling of pii-inventory.md)"

# 5. a logger per site block — the five hostnames
for host in $HOSTS; do
  n="$(count_re "$json_reh" "\"${host}\.trades\.test\":\[\"log[0-9]+\"\]")"
  check "$([ "$n" -ge 1 ] && echo 0 || echo 1)" "site ${host}.trades.test has an access logger"
done

# --- per-host segmentation ---------------------------------------------------------------
# Every route Caddy derives from a site block starts with its host matcher — the MAIN route
# (the site's handlers) and, inside the server's `errors` block, the ERROR route (the
# handle_errors of that site). A newline before each host matcher turns the compact JSON into
# one line per route; the error route is the one carrying the `static_response` handler.
# awk's gsub with `&` is portable (BSD awk on the macOS dev machine, GNU awk on the CI runner).
segmented="$(printf '%s' "$json_reh" | awk '{gsub(/\{"match":\[\{"host":\[/, "\n&"); print}')"
segment() {   # segment <host> <main|error> → the one route line
  if [ "$2" = error ]; then
    printf '%s\n' "$segmented" | grep -F "\"${1}.trades.test\"" | grep -F '"handler":"static_response"' | head -1
  else
    printf '%s\n' "$segmented" | grep -F "\"${1}.trades.test\"" | grep -vF '"handler":"static_response"' | head -1
  fi
}
n_seg="$(printf '%s\n' "$segmented" | grep -c '^{"match":\[{"host":\[' || true)"
check "$([ "$n_seg" = 10 ] && echo 0 || echo 1)" "ten host routes in the adapted config (5 sites + 5 error lanes; found $n_seg)"

for host in $HOSTS; do
  main="$(segment "$host" main)"; err="$(segment "$host" error)"
  check "$([ -n "$main" ] && echo 0 || echo 1)" "${host}.: main route present"
  check "$([ -n "$err" ] && echo 0 || echo 1)" "${host}.: error lane (handle_errors) present"

  # 6. the floor, DEFERRED form, on both lanes — the `?` prefix adapts to
  #    "require":{"headers":{"<Field>":null}} + "set":{"<Field>":[...]}
  missing_main=""; missing_err=""
  for h in $FLOOR_HEADERS; do
    pat="\"require\":{\"headers\":{\"${h}\":null}},\"set\":{\"${h}\":["
    [ "$(count "$main" "$pat")" -ge 1 ] || missing_main="$missing_main $h"
    [ "$(count "$err" "$pat")" -ge 1 ] || missing_err="$missing_err $h"
  done
  check "$([ -z "$missing_main" ] && echo 0 || echo 1)" "${host}.: security floor (deferred ?) at site level — all six headers${missing_main:+ (missing:$missing_main)}"
  check "$([ -z "$missing_err" ] && echo 0 || echo 1)" "${host}.: security floor (deferred ?) inside handle_errors — all six headers${missing_err:+ (missing:$missing_err)}"

  # 7. the error lane: bare status body + private, no-store
  n_cc="$(count "$err" '"set":{"Cache-Control":["private, no-store"]}')"
  n_body="$(count "$err" '"body":"{http.error.status_code} {http.error.status_text}"')"
  check "$([ "$n_cc" -ge 1 ] && [ "$n_body" -ge 1 ] && echo 0 || echo 1)" "${host}.: error lane answers the bare status line with Cache-Control: private, no-store"

  # 8. noindex on every site
  n_robots="$(count "$main" '"X-Robots-Tag":["noindex"]')"
  check "$([ "$n_robots" -ge 1 ] && echo 0 || echo 1)" "${host}.: X-Robots-Tag noindex"

  # 9. basic auth on exactly app. and mail.
  n_auth="$(count "$main" '"handler":"authentication"')"
  case " $AUTH_HOSTS " in
    *" $host "*) check "$([ "$n_auth" -ge 1 ] && echo 0 || echo 1)" "${host}.: basic auth PRESENT (BR-18)" ;;
    *)           check "$([ "$n_auth" = 0 ] && echo 0 || echo 1)" "${host}.: basic auth ABSENT — Authorization header is the API's / presigned / hub lane (BR-18)" ;;
  esac
done
n_auth_total="$(count "$json_reh" '"handler":"authentication"')"
check "$([ "$n_auth_total" = 2 ] && echo 0 || echo 1)" "exactly two basic-auth handlers in the whole config (app. and mail.; found $n_auth_total)"

# 10. no unconditional CSP anywhere; exactly one unconditional HSTS writer (the storage host)
n_csp_set="$(count "$json_reh" '"set":{"Content-Security-Policy":[')"
n_csp_deferred="$(count "$json_reh" '"require":{"headers":{"Content-Security-Policy":null}},"set":{"Content-Security-Policy":[')"
check "$([ "$n_csp_set" = "$n_csp_deferred" ] && [ "$n_csp_set" -ge 10 ] && echo 0 || echo 1)" "every Content-Security-Policy writer is a deferred ? default (set=$n_csp_set deferred=$n_csp_deferred, need equal and >=10) — CSP is application-emitted"
n_hsts_all="$(count "$json_reh" '"Strict-Transport-Security":["max-age=63072000; includeSubDomains"]')"
n_hsts_deferred="$(count "$json_reh" '"require":{"headers":{"Strict-Transport-Security":null}},"set":{"Strict-Transport-Security":[')"
n_hsts_uncond=$((n_hsts_all - n_hsts_deferred))
check "$([ "$n_hsts_uncond" = 1 ] && echo 0 || echo 1)" "exactly one unconditional Strict-Transport-Security writer — the storage host (found $n_hsts_uncond; $n_hsts_deferred deferred floor writers)"

if [ "$fails" -gt 0 ]; then
  echo "✗ check-caddyfile: $fails check(s) failed" >&2
  exit 1
fi
echo "→ check-caddyfile: OK"
